import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Flex as RobotoFlex } from 'next/font/google';
import Header from './components/Header';
import Footer from './components/Footer';

const robotoFlex = RobotoFlex({
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${robotoFlex.variable} flex min-h-screen w-screen flex-col overflow-hidden bg-slate-900 text-cyan-300`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
