import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Flex as RobotoFlex } from 'next/font/google';

const robotoFlex = RobotoFlex({
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${robotoFlex.variable} bg-slate-900 text-cyan-300`}>
        {children}
      </body>
    </html>
  );
}
